version: "3"
services:
    app:
        build:
            context: .
        ports:
            - "3000:3000"
        depends_on:
            - db
        environment:
            DB_HOST: db
            DB_USER: postgres
            DB_NAME: postgres
            DB_PASSWORD: 12321
            DB_PORT: 5432
    db:
        image: postgres
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 12321
        ports:
            - "5432:5432"
